name: Daily Cron Job

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule to run at 0 UTC daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt  # Modify this according to your project's requirements

      - name: Run Python script
        run: python main.py  
